id: I76C876CD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T07:54:21+00:00'
last_modified: '2022-06-07T18:42:56.957711+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG10253
  title: འབྲུག་པ་ཀུན་དགའ་ལེགས་པའི་རྣམ་ཐར་དང་ཉམས་མགུར་དང་ཞལ་གདམས་སོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    C38F:
      image_group_id: I1KG10255
      title: ''
      total_pages: 718
      order: 1
      base_file: C38F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
