id: I76C876CD
legacy_id: P003261
ocr_import_info:
  bdrc_scan_id: W1KG10253
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T07:49:27'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T02:30:00.619526+00:00'
last_modified: 2022-08-31 10:30:48.161273
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG10253
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG10253
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འབྲུག་པ་ཀུན་དགའ་ལེགས་པའི་རྣམ་ཐར་དང་ཉམས་མགུར་དང་ཞལ་གདམས་སོགས།
  author: འབྲུག་པ་ཀུན་ལེགས།
statistics:
  ocr_word_mean_confidence_index: 0.7002141636341213
  ocr_word_median_confidence_index: 0.75
quality: null
bases:
  I1KG10255:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10255
      total_pages: 718
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG10255.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.7002141636341213
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
