id: P003261
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 10:51:01.589817
source_metadata:
  id: bdr:W1KG10253
  title: འབྲུག་པ་ཀུན་དགའ་ལེགས་པའི་རྣམ་ཐར་དང་ཉམས་མགུར་དང་ཞལ་གདམས་སོགས།
  author: ''
  volumes:
    5819cd00bffa4d76a67931771f2d474d:
      image_group_id: I1KG10255
      title: ''
      volume_number: 1
      total_pages: 718
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
